# This is a config for E2B sandbox template.
# You can use template ID (jg023m6krci5beckxs6s) or template name (web-maker-test) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("web-maker-test") # Sync sandbox
# sandbox = await AsyncSandbox.create("web-maker-test") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('web-maker-test')

team_id = "9f4a2dd2-85c2-48b5-bcb2-d795d13e59ac"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "web-maker-test"
template_id = "jg023m6krci5beckxs6s"
